### ISSUE TITLE
SQL parsing production TODO's

### ISSUE THREAD

**Issue by jan-kelemen** [jan-kelemen/melinda#35]
- [ ] Limit \<regular identifier\>, \<delimited identifer\> and \<Unicode delimited identifier\> to 128 parts
- [ ] \<Unicode delimited identifier\> should support constants which don't fit in a single character
- [ ] Error handling in scan productions
